spring:
  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  datasource:
    url: jdbc:mysql://localhost:3306/attendance
    username: root
    password: akram
